In [1]:
# Start 18.30 // 01.01.2023
# End 2.00  /// 02.01.2023

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# Importing Dataset
# 1.1 Please import data set Titanic - Machine Learning from Disaster from https://www.kaggle.com 
df = pd.read_csv('train.csv')

In [3]:
# 1.2 Realize Exploratory Data Analysis (EDA) by using explanation code 
# https://colab.research.google.com/drive/1CPDcPsg389I_HR6k7WwF1eFEDLaCixZz#scrollTo=iyxqefzIFkc8
#  For Categorical data: https://colab.research.google.com/drive/15GPIyxBdHHkq550GIG19j9vBk-vV4ohs (10 points)
df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [4]:
# My dataset and info about it
print("Train Dataset")
print(df.Survived.value_counts())
print(df.isnull().sum())
df

Train Dataset
0    549
1    342
Name: Survived, dtype: int64
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
# Drop cabin because it is not important and replacing missing values with mean and mode values
df = df.drop(columns='Cabin', axis=1)
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [6]:
# Convert gender and Embraked into int values
df.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)

In [7]:
# Then select a group of parameters for a model with two or more Independent variables and one 
# Dependent variable=Survived. (10 points)

# Splitting data to X and Y
X = df.drop(columns = ['PassengerId','Name','Ticket','Survived'],axis=1)
Y = df['Survived']

In [8]:
# And splitting X and Y in four variables

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=2)

print(len(X_train), len(X_test), len(Y_train), len(Y_test))

712 179 712 179


In [9]:
# Creating and Train Linear Model
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [10]:
x_test_pred = model.predict(X_test) 
r2_score(Y_test, x_test_pred)

0.3254525179332991

In [11]:
x_train_pred = model.predict(X_train) 
r2_score(Y_train, x_train_pred)

0.4114075775997431

In [12]:
# Honestly ,this must give as an precentage of accuracy of prediction ,
# but it raise up an error and I replace it with upper variants(and they are is almost right)

# X_train_prediction = model.predict(X_train)

# training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
# print('Accuracy score of training data : ', training_data_accuracy)

# X_test_prediction = model.predict(X_test)
# test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
# print('Accuracy score of test data : ', test_data_accuracy)

In [13]:
# Testing to predicting

test_data = (3,0,35,0,0,8.05,0)
test_data_to_numpy = np.asarray(test_data)
test_data_to_2D = test_data_to_numpy.reshape(1,-1) # Transform 1D array to 2D array

In [14]:
prediction = model.predict(test_data_to_2D)
print(prediction)
if prediction[0]>=1:
    print("Alive")
else:
    print("Dead")

[0.03977003]
Dead
/shared-libs/python3.9/py/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [15]:
# Task 2

iris_dataset = load_iris()
print(iris_dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [16]:
iris = sns.load_dataset('iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [17]:
# 2.2 Convert Species columns in a numerical column of the iris dataframe. 
# To encode this data map convert each value to a number. e.g. Iris-setosa:0, 
# Iris-versicolor:1, and Iris-virginica: 2. 
iris.replace({'species':{'setosa':0,'versicolor':1,'virginica':2}}, inplace=True)
iris

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [18]:
# 2.1 Write a Python program to split the iris dataset into its attributes (X) and labels (y). 
# The X variable contains the first four columns (i.e. attributes) and y contains the labels of the dataset.
# 10 points)

x_train, x_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'],test_size=0.2, random_state=0)
print("x_train: {}, y_train: {} ".format(x_train.shape, y_train.shape[0]))
print("x_test: {},  y_test: {} ".format(x_test.shape,y_test.shape[0]))

x_train: (120, 4), y_train: 120 
x_test: (30, 4),  y_test: 30 


In [19]:
# Now print the iris dataset into 80% train data and 20% test data. Out of a total 150 records,
#  the training set will contain 120 records and the test set contains 30 of those records. Print
#   both datasets. (10 points)/up
x_train

array([[6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2

In [20]:
y_train

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [21]:
# 2.3 Predict the response for the test dataset (SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm) 
# using the K Nearest Neighbor Algorithm. Use 5 as the number of neighbors. (10 points)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [22]:
# 2.4 Train or fit the data into the model and calculate the accuracy of the model using the
#  K Nearest Neighbor Algorithm. (10 points)

X_new = np.array([[1, 2, 3, 1]])
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print(": {}".format(
iris_dataset['target_names'][prediction]))

Prediction: [0]
: ['setosa']


In [23]:
y_pred = knn.predict(x_test)
print("Prediction for test set:\n {}".format(y_pred))

Prediction for test set:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 2 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [24]:
print("accuracy: {:.2f}".format(np.mean(y_pred == y_test)))

accuracy: 0.97


In [25]:
# 2.5 Train or fit the data into the model and using the K Nearest Neighbor Algorithm calculate 
# the performance for different values of k (from 1 to 10). (10 points)

knn1 = KNeighborsClassifier(n_neighbors=4)
knn1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [26]:
y_pred1 = knn1.predict(x_test)
print("Prediction for test set:\n {}".format(y_pred1))

Prediction for test set:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [27]:
print("accuracy: {:.2f}".format(np.mean(y_pred1 == y_test)))

accuracy: 1.00


In [28]:
x=[]
for i in range(1, 11):
    knn1 = KNeighborsClassifier(n_neighbors=i)
    knn1.fit(x_train, y_train)
    y_pred1 = knn1.predict(x_test)
    x.append(np.mean(y_pred1 == y_test))
x

[1.0,
 0.9666666666666667,
 0.9666666666666667,
 1.0,
 0.9666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=29550934-a2ef-4615-a6c5-b44f88c596ec' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>